name: Deploy Dirtviz Slack Bot to Lambda

on:
  push:
    branches: [main] # deploy when main is updated

permissions:
  id-token: write # This is required for OIDC authentication
  contents: read # This is required to checkout the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          mkdir package
          pip install -r requirements.txt -t package/

      - name: Copy source code
        run: |
          cp -r src/dirtviz_slack_bot package/
          cp lambda_function.py package/

      - name: Zip package
        run: |
          cd package
          zip -r ../function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # change if needed
          command: |
            lambda update-function-code \
              --function-name DirtvizSlackBot \
              --zip-file fileb://function.zip
