name: Deploy Dirtviz Slack Bot to Lambda

on:
  push:
    branches: [main] # deploy when main is updated

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and package
        run: |
          pip install --target ./package -r requirements.txt
          cd package
          zip -r ../function.zip .
          cd ..
          zip -g function.zip lambda_function.py
          zip -g function.zip -r src

      - name: Test Lambda Handler
        run: |
          docker run --rm -v "$PWD":/var/task public.ecr.aws/lambda/python:3.11 lambda_function.lambda_handler

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v1.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1
          function_name: dirtviz-slack-bot
          zip_file: function.zip
